### ISSUE TITLE
Feedback for First Model/Views

### ISSUE THREAD

**Issue by ChrisWilson2** [ChrisWilson2/06-24-nannies#19]

**Comment by sumeetjain** [comment]
- [ ] Remove all interrupts (e.g. `binding.pry`) from code
- [ ] [This method](https://github.com/ChrisWilson2/06-24-nannies/blob/master/database_class_methods.rb#L43-L53) doesn't actually return an Array containing the custom objects.
- [ ] Change order of files being loaded so that your work (e.g. controllers/models/etc) is loaded _after_ libraries like SQLite and ActiveSupport. https://github.com/ChrisWilson2/06-24-nannies/blob/master/app.rb
- [ ] Validation should be done in the model. What's achieved by [this code](https://github.com/ChrisWilson2/06-24-nannies/blob/master/controllers/kids.rb#L29) could be achieved by a method in the model. You would pass the information stored in `params` into that method.

**Comment by sumeetjain** [comment]
The validation could be better still. Have the `valid?` method check all the things at once.
